### PR TITLE
Add individual test duration to report

### PR DESCRIPTION
**Pull request by nivnahmias**
Knowing how long each test runs is very helpful in figuring out if a certain test is problematic.
This feature is available in other reporters (teamcity)

### CODE REVIEW

**Comment by nivnahmias** [comment]
i'm not sure why tests are failing, @AndreyBelym / @AlexanderMoskovkin  any thoughts?
Perhaps the chalk package now uses ECMA2015 syntax? (const)
Doesn't seem related to my PR, any reason we're testing against node 0.10 & 0.12?

**Comment by Ahnenerbe154** [comment]
https://www.npmjs.com/package/testcafe-reporter-time-spec

**Comment by AndreyBelym** [comment]
I apologize for the delayed response. We need to discuss with the team if we want to always include the individual test time in the default reports.

**Comment by Asgator** [comment]
@AndreyBelym that need, bec that help for look what a test slowly and optimize he.

**Comment by AndreyBelym** [comment]
Thank you for your feedback. Right now, we do not want to introduce any changes to the report format. I also want to express my gratitude to @Asgator for implementing the requested feature in the [testcafe-reporter-time-spec](https://www.npmjs.com/package/testcafe-reporter-time-spec). You can use it as a drop-in replacement if you want to see elapsed times for each test.

**Pull request closed without merging**
